import unittest
import json
import os

class TestDataIntegrity(unittest.TestCase):

    def test_sample_tickets_exist_and_valid(self):
        """Verify that the sample tickets JSON file exists and contains valid JSON."""
        file_path = "data/sample_tickets.json"
        self.assertTrue(os.path.exists(file_path), f"{file_path} does not exist.")
        
        with open(file_path, "r") as f:
            data = json.load(f)
            self.assertIsInstance(data, list, "Sample tickets must be formatted as a JSON list array.")
            if len(data) > 0:
                self.assertIn("id", data[0])
                self.assertIn("subject", data[0])
                self.assertIn("body", data[0])

    def test_output_directory_structure(self):
        """Verify that the output data file has been safely generated by the agent."""
        file_path = "output/triaged_tickets.json"
        self.assertTrue(os.path.exists(file_path), f"Output file not found. Run agent.py first.")

if __name__ == "__main__":
    unittest.main()
